### PR TITLE
[Draft] GraphQL Integration Tests

### PR DESCRIPTION
**Pull request by Jonasdoubleyou**
IMO this adds way more coverage to our codebase as our implementations are rather "along workflows", thus creating unit tests is usually hard and adds little coverage. The integration tests cover less logic, however they at least ensure that nothing breaks in serious ways. 

I'm not quite sure how to integrate this into CI/CD as running those tests without a database / uplink is difficult. 

resolves https://github.com/corona-school/project-user/issues/447

### CODE REVIEW

**Comment by Jonasdoubleyou** [comment]
@lsc0498 @Leo310 what do you think of this (and having integration tests in general)?

**Comment by Leo310** [comment]
I think integration tests are a good idea even if it adds more work. The testing framework you made looks quite nice. Maybe a way to inject results of previous queries (e.g. pupilId) into the next one, could be via a context variable that gets passed to each runner (I need to look up what comment binding variables are).

And why without a database? Cant we just deploy one in the CI/CD process? Or use sqlite or something that can be deployed in the application itself?

**Review by lsc0498 — APPROVED** [review]
Looks good! I think the best would be to integrate this to our GitHub commit checks.

**Comment by lsc0498** [comment]
I think we already have some kind of testing database 🤔

**Comment by Jonasdoubleyou** [comment]
Ah, true, actually I overlooked that. Indeed we do start a Postgres with every CI run

**Pull request merged**
