### PR TITLE
fix(automatic-promotion): moved promotion logic into common

### PR DESCRIPTION
**Pull request by Leo310**

### CODE REVIEW

**Review by Jonasdoubleyou — APPROVED** [review]
please also adapt the text of the approve button in Retool, to make support aware that the button also publishes & promotes

**Comment by Leo310** [comment]
image
Why are there even two buttons for this? Atm both would do the same thing no?

**Comment by Jonasdoubleyou** [comment]
yeah they would 😅

**Comment by Jonasdoubleyou** [comment]
yes makes sense

**Comment by Leo310** [comment]
OK, I removed it in v1.12.0. If this is fine, I will send a message to tech-updates @Jonasdoubleyou

**Pull request merged**
