### PR TITLE
/register/checkEmail endpoint + rate-limiting

### PR DESCRIPTION
**Pull request by realmayus**
Incorporates changes from https://github.com/corona-school/backend/pull/182
+ rate-limiting

### CODE REVIEW

**Comment by realmayus** [comment]
@geroembser How do I add the new endpoint to the docs? The CI gives me this error: https://github.com/corona-school/backend/pull/184/checks?check_run_id=2375186324

All I added docs-wise so far is this:
https://github.com/corona-school/backend/blob/feat/%23183/web/controllers/registrationController/index.ts#L1115-L1134

I also saw that some kind of API version is mentioned in the docs. Do I need to increase that version number, since I added that endpoint?

**Comment by geroembser** [comment]
> The CI gives me this error: https://github.com/corona-school/backend/pull/184/checks?check_run_id=2375186324

@realmayus It looks like `StatusOK` is the problem. `StatusOk` should work instead, as it was already used in the past.

**Comment by geroembser** [comment]
@realmayus if you wanna test the docs locally, you can run `npm run web:docs`. It may output some warnings, but as long as the return code is ok, the Github Action will accept this. So basically `(npm run web:docs > /dev/null && echo 'DOC OK') || echo 'DOC ERROR'` should be a simple test that you can use on your computer to "check" the docs. Probably better than pushing and waiting for Github :joy:

**Review by geroembser — APPROVED** [review]
Looks good to me 👍

**Pull request merged**
